version: '3.8'

services:
  # Spark Master
  spark-master:
    image: bitnami/spark:3.5.3
    container_name: spark-master
    environment:
      - SPARK_MODE=master
      - SPARK_MASTER_HOST=spark-master
      - SPARK_MASTER_PORT=7077
    ports:
      - "8080:8080"  # Spark UI
      - "7077:7077"  # Spark Master Port
    networks:
      - spark-network

  # Spark Worker (you can scale this to more workers)
  spark-worker:
    image: bitnami/spark:3.5.3
    container_name: spark-worker
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER=spark://spark-master:7077
    networks:
      - spark-network
  
  # PostgreSQL
  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"  # PostgreSQL default port
    networks:
      - spark-network

  minio:
    image: quay.io/minio/minio
    restart: always
    command: server /data --console-address ":9001"
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
      - MINIO_LOG_LEVEL=debug
    volumes:
      - minio_data:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    networks:
      - spark-network


  test:
    build: .
    depends_on:
      - postgres
    networks:
      - spark-network
    environment:
      - DEVELOPMENT=False

  # Network configuration
networks:
  spark-network:
    driver: bridge

volumes:
  minio_data:

